/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eprojectsemii;

import data.Questions;
import entities.Question;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import utilities.SQLUtil;

/**
 *
 * @author Fozg
 */
public class dlgViewQuestion extends javax.swing.JDialog {

    /**
     * Creates new form dlgViewQuestion
     */
    private DefaultTableModel dtm;
    private Question[] question;
    Questions q = new Questions();

    public dlgViewQuestion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        Questions q = new Questions();
//        List l = q.getAllQuestions();
//        Question[] qq =(Question[])l.toArray();
//        DefaultTableModel dtm = new DefaultTableModel(new String[]{"ID", "Size", "Title"}, 0);
//        for (Question ques:qq){
//        dtm.addRow(new Object[]{ques.getQuestionID(),ques.getQuestionSize(),ques.getQuestionTitle()});
//        
//        }
//        tQuestion.setModel(dtm);

        dtm = new DefaultTableModel(
                new String[]{"Title", "ID", "Difficult", "Size"}, 0);
//        try {
//            String cmd = "select * from Question ";
//            ResultSet rs = new SQLUtil().executeResultSet(cmd);
//            dtm.setRowCount(0);
//            while (rs.next()) {
//                String id = rs.getString("QuestionID");
//                int size = rs.getInt("QuestionSize");
//                String title = rs.getString("QuestionTitle");
//                String code = rs.getString("QuestionCode");
//                String keyacross = rs.getString("QuestionKeyAcross");
//                String keydown = rs.getString("QuestionKeyDown");
//                String hintacross = rs.getString("QuestionHintAcross");
//                String hintdown = rs.getString("QuestionHintDown");
//                int diff = rs.getInt("QuestionDifficult");
//                //Them mot dong gom cac du lieu nay vao bang
//                dtm.addRow(new Object[]{id, size, title});
//
//            }
//            //Set the model for the table.
//            tQuestion.setModel(dtm);
//        } catch (SQLException ex) {
//            Logger.getLogger(dlgViewQuestion.class.getName()).log(Level.SEVERE, null, ex);
//        }

        question = q.getAllQuestions();
        List<Question> queslist = q.getAllQuestionsList();

        for (Question qq : queslist) {
            dtm.addRow(new Object[]{qq.getQuestionTitle(), qq.getQuestionID(), qq.getQuestionDifficult(), qq.getQuestionSize()});
        }
//        for (Question qq : q.getAllQuestions()) {
//            dtm.addRow(new Object[]{qq.getQuestionTitle(), qq.getQuestionID(), qq.getQuestionDifficult(), qq.getQuestionSize()});
//        }
        tQuestion.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tQuestion = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lbKeywordacross = new javax.swing.JLabel();
        lbHintAcross = new javax.swing.JLabel();
        lbHintDown = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHintAcross = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHintDown = new javax.swing.JTextArea();
        lbKeyworddown = new javax.swing.JLabel();
        cbSize = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbDifficult = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Question manager");
        setResizable(false);

        jLabel3.setText("Find");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Add new");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tQuestion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tQuestionMouseClicked(evt);
            }
        });
        tQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tQuestionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tQuestion);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Design"));

        pnMain.setToolTipText("");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbKeywordacross.setText("Keywords across:");

        lbHintAcross.setText("Hint across:");

        lbHintDown.setText("Hint down:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtHintAcross.setEditable(false);
        txtHintAcross.setColumns(20);
        txtHintAcross.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHintAcross.setRows(5);
        jScrollPane2.setViewportView(txtHintAcross);

        txtHintDown.setEditable(false);
        txtHintDown.setColumns(20);
        txtHintDown.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHintDown.setRows(5);
        jScrollPane3.setViewportView(txtHintDown);

        lbKeyworddown.setText("Keywords down:");

        cbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "4x4", "6x6", "8x8" }));

        jLabel1.setText("Difficult");

        cbDifficult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Easy", "Normal", "Hard" }));

        jLabel2.setText("Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbKeywordacross)
                    .addComponent(lbKeyworddown)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHintDown)
                                    .addComponent(lbHintAcross))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete)
                            .addComponent(jLabel2)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbKeywordacross)
                                .addGap(21, 21, 21)
                                .addComponent(lbKeyworddown)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbHintAcross))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbHintDown))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String id;

    private void changeselecd() {
        id = dtm.getValueAt(tQuestion.getSelectedRow(), 1).toString();
        // lbCheck.setText("ID:" + id + "");
        this.setTitle("Question Manager - " + id);
        pnMain.removeAll();
        pnMain.repaint();
        Questions quess = new Questions();
        Question ques = quess.getQuestionByID(id);
        // jbb.setVisible(true);

//        String s = question[tQuestion.getSelectedRow()].getQuestionCode();
//        int size = question[tQuestion.getSelectedRow()].getQuestionSize();
//
//        pnPlay pnP = new pnPlay();
//        pnP.setWords(s);
//        pnP.setSizexy(size);
//
//        pnMain.add(pnP);
//        txtHintAcross.setText(question[tQuestion.getSelectedRow()].getQuestionHintAcross());
//        txtHintDown.setText(question[tQuestion.getSelectedRow()].getQuestionHintDown());
//        lbKeywordacross.setText("Keywords across:" + question[tQuestion.getSelectedRow()].getQuestionKeyAcross());
//        lbKeyworddown.setText("Keywords down: " + question[tQuestion.getSelectedRow()].getQuestionKeyDown());
        String s = ques.getQuestionCode();
        int size = ques.getQuestionSize();

        pnPlay pnP = new pnPlay();
        pnP.setWords(s);
        pnP.setSizexy(size);

        pnMain.add(pnP);
        txtHintAcross.setText(ques.getQuestionHintAcross());
        txtHintDown.setText(ques.getQuestionHintDown());
        lbKeywordacross.setText("Keywords across:" + ques.getQuestionKeyAcross());
        lbKeyworddown.setText("Keywords down: " + ques.getQuestionKeyDown());
        //   pnP.setSize(300, 300);
        pnP.setVisible(true);
        pnP.DrawToManager();
        pack();        // TODO add your handling
    }
    private void tQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tQuestionMouseClicked

        changeselecd();

    }//GEN-LAST:event_tQuestionMouseClicked

    private void tQuestionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tQuestionKeyReleased

        changeselecd();
    }//GEN-LAST:event_tQuestionKeyReleased
    String searchSize = "";
    String searchDiff = "";
    String searchkeyword = "";
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        FrmMain f = new FrmMain();
        dlgNewQuestionFinal cp = new dlgNewQuestionFinal(f, true);
        cp.setVisible(true);
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        dtm = new DefaultTableModel(
                new String[]{"Title", "ID", "Difficult", "Size"}, 0);

        Questions q = new Questions();

        switch (cbSize.getSelectedIndex()) {
            case 0:
                searchSize = "";
                break;
            case 1:
                searchSize = "4";
                break;
            case 2:
                searchSize = "6";
                break;
            case 3:
                searchSize = "8";
                break;
        }
        switch (cbDifficult.getSelectedIndex()) {
            case 0:
                searchDiff = "";
                break;
            case 1:
                searchDiff = "1";
                break;
            case 2:
                searchDiff = "2";
                break;
            case 3:
                searchDiff = "3";
                break;
        }

        searchkeyword = txtSearch.getText();

        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refresh() {
        dtm = new DefaultTableModel(
                new String[]{"Title", "ID", "Difficult", "Size"}, 0);
        question = q.getAllQuestions();
        List<Question> queslist = q.AdvancedSearch(searchSize, searchDiff, searchkeyword);

        for (Question qq : queslist) {
            dtm.addRow(new Object[]{qq.getQuestionTitle(), qq.getQuestionID(), qq.getQuestionDifficult(), qq.getQuestionSize()});
        }

        tQuestion.setModel(dtm);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        FrmMain f = new FrmMain();
        dlgUpdate cp = new dlgUpdate(f, true, id);
        // cp.setQuestionid(id);
        cp.DrawAgain();
        cp.setVisible(true);
        refresh();
    }//GEN-LAST:event_btnEditActionPerformed

    //delete question
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        q.DeleteQuestion(id);
        refresh();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgViewQuestion dialog = new dlgViewQuestion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox cbDifficult;
    private javax.swing.JComboBox cbSize;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbHintAcross;
    private javax.swing.JLabel lbHintDown;
    private javax.swing.JLabel lbKeywordacross;
    private javax.swing.JLabel lbKeyworddown;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tQuestion;
    private javax.swing.JTextArea txtHintAcross;
    private javax.swing.JTextArea txtHintDown;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
