/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eprojectsemii;

import data.Questions;
import data.Records;
import data.Saveds;
import entities.Question;
import entities.Record;
import entities.Saved;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.QuadCurve2D;
import java.io.File;
import java.util.List;
import java.util.Random;
import javax.print.attribute.standard.Media;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Fozg
 */
public class FrmMain extends javax.swing.JFrame {

    Timer t = null;
    int ss = 300;
    int hh, mm, se = 0;
    Question question;
    int totalword;
    int role = 3;
    String username;
    int userID = 0;
    int size = 0;
    int diff = 0;
    Saveds saved = new Saveds();

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();

        //Phan quyen khi vao
        btnLogin.setVisible(true);
        txtLogin.setText("Hello: " + "Guest");
        mnQuestion.setVisible(false);
        mnRecord.setVisible(false);
        btnSave.setVisible(false);
        mnProfile.setVisible(false);
        mnAccount.setVisible(false);
        btnFinsh.setEnabled(false);
        btnPause.setEnabled(false);
        btnResume.setEnabled(false);


        t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                --ss;
                lbTime.setText(display(ss));
                if (ss == 0) {
                    //  lbTime.setText("05:0");
                    lbTime.setText("Time Out");
                    lbTime.setForeground(Color.RED);
                    t.stop();
                    finish();
                }

            }
        });

        btnResume.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar(){

            ImageIcon icon = new ImageIcon("src/icons/bgmenu.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnNewgame = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        btnFinsh = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnHighScore = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHintAcross = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHintDown = new javax.swing.JTextArea();
        lbQuestionName = new javax.swing.JLabel();
        lbTotalword = new javax.swing.JLabel();
        lbQuestionID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/icons/crossword.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        pnMain = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        btnColorGreen = new javax.swing.JButton();
        btnChangeColor2 = new javax.swing.JButton();
        btnChangeColor3 = new javax.swing.JButton();
        btnChangeColor4 = new javax.swing.JButton();
        btnChangeColor5 = new javax.swing.JButton();
        btnChangecolor6 = new javax.swing.JButton();
        lbTime = new javax.swing.JTextField();
        jToolBar3 = new javax.swing.JToolBar();
        btnMusic = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnQuestion = new javax.swing.JMenu();
        mnNewQuestion = new javax.swing.JMenuItem();
        mnViewQuestion = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnRecord = new javax.swing.JMenu();
        mnViewallrecord = new javax.swing.JMenuItem();
        mnAccount = new javax.swing.JMenu();
        mnProfile = new javax.swing.JMenuItem();
        mnHistory = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 540));
        setMinimumSize(new java.awt.Dimension(1000, 540));
        setPreferredSize(new java.awt.Dimension(1000, 540));
        setResizable(false);

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);

        btnNewgame.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnNewgame.setForeground(new java.awt.Color(255, 255, 255));
        btnNewgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newgame.png"))); // NOI18N
        btnNewgame.setToolTipText("");
        btnNewgame.setBorderPainted(false);
        btnNewgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewgame.setFocusable(false);
        btnNewgame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewgame.setMaximumSize(new java.awt.Dimension(117, 57));
        btnNewgame.setMinimumSize(new java.awt.Dimension(117, 57));
        btnNewgame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewgameActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewgame);

        btnPause.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnPause.setForeground(new java.awt.Color(255, 255, 255));
        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pause.png"))); // NOI18N
        btnPause.setBorderPainted(false);
        btnPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPause.setFocusable(false);
        btnPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPause);

        btnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resume.png"))); // NOI18N
        btnResume.setBorderPainted(false);
        btnResume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResume.setFocusable(false);
        btnResume.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResume.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnResume);

        btnFinsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/finish.png"))); // NOI18N
        btnFinsh.setFocusable(false);
        btnFinsh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinsh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinshActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFinsh);

        btnOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/option.png"))); // NOI18N
        btnOption.setFocusable(false);
        btnOption.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOption.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOption);

        btnHighScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hightsocre.png"))); // NOI18N
        btnHighScore.setFocusable(false);
        btnHighScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighScore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHighScore);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save1.png"))); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        jPanel1.setOpaque(false);

        txtHintAcross.setEditable(false);
        txtHintAcross.setBackground(new java.awt.Color(240, 240, 240));
        txtHintAcross.setColumns(20);
        txtHintAcross.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHintAcross.setRows(5);
        txtHintAcross.setBorder(null);
        jScrollPane2.setViewportView(txtHintAcross);

        txtHintDown.setEditable(false);
        txtHintDown.setBackground(new java.awt.Color(240, 240, 240));
        txtHintDown.setColumns(20);
        txtHintDown.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHintDown.setRows(5);
        txtHintDown.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(txtHintDown);

        lbQuestionName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuestionName.setForeground(new java.awt.Color(0, 0, 153));
        lbQuestionName.setText("Question:");

        lbTotalword.setText("Total words: ");

        lbQuestionID.setText("Question ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQuestionName)
                            .addComponent(lbTotalword)
                            .addComponent(lbQuestionID))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lbQuestionName)
                .addGap(10, 10, 10)
                .addComponent(lbQuestionID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jToolBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onoff.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        btnColorGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/000-165-224.png"))); // NOI18N
        btnColorGreen.setFocusable(false);
        btnColorGreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColorGreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColorGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorGreenActionPerformed(evt);
            }
        });
        jToolBar2.add(btnColorGreen);

        btnChangeColor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/181-096-166.png"))); // NOI18N
        btnChangeColor2.setFocusable(false);
        btnChangeColor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeColor2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangeColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeColor2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnChangeColor2);

        btnChangeColor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/246-83-20.png"))); // NOI18N
        btnChangeColor3.setFocusable(false);
        btnChangeColor3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeColor3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangeColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeColor3ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnChangeColor3);

        btnChangeColor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/255-187-000.png"))); // NOI18N
        btnChangeColor4.setFocusable(false);
        btnChangeColor4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeColor4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangeColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeColor4ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnChangeColor4);

        btnChangeColor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/124-187-000.png"))); // NOI18N
        btnChangeColor5.setFocusable(false);
        btnChangeColor5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeColor5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangeColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeColor5ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnChangeColor5);

        btnChangecolor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/107-107-107.png"))); // NOI18N
        btnChangecolor6.setFocusable(false);
        btnChangecolor6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangecolor6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangecolor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangecolor6ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnChangecolor6);

        lbTime.setEditable(false);
        lbTime.setBackground(new java.awt.Color(255, 255, 204));
        lbTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTime.setForeground(new java.awt.Color(0, 153, 153));
        lbTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbTime.setText("--:--");
        jToolBar2.add(lbTime);

        jToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        btnMusic.setText("Play music");
        btnMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicActionPerformed(evt);
            }
        });
        jToolBar3.add(btnMusic);

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton1);

        lbInfo.setText(":");
        jToolBar3.add(lbInfo);

        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(153, 0, 0));
        txtLogin.setText("Hello: Guest");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        mnQuestion.setText("Question");

        mnNewQuestion.setText("New Question");
        mnNewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNewQuestionActionPerformed(evt);
            }
        });
        mnQuestion.add(mnNewQuestion);

        mnViewQuestion.setText("View Question");
        mnViewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnViewQuestionActionPerformed(evt);
            }
        });
        mnQuestion.add(mnViewQuestion);

        jMenuItem4.setText("Delete question");
        mnQuestion.add(jMenuItem4);

        jMenuBar1.add(mnQuestion);

        mnRecord.setText("Record");
        mnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecordActionPerformed(evt);
            }
        });

        mnViewallrecord.setText("View all records");
        mnViewallrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnViewallrecordActionPerformed(evt);
            }
        });
        mnRecord.add(mnViewallrecord);

        jMenuBar1.add(mnRecord);

        mnAccount.setText("Account");

        mnProfile.setText("Profile");
        mnAccount.add(mnProfile);

        mnHistory.setText("History");
        mnAccount.add(mnHistory);

        jMenuBar1.add(mnAccount);

        jMenu3.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        //exit
    }//GEN-LAST:event_jMenu1ActionPerformed
    Questions q = new Questions();
    pnPlay pnP;
    Color c = new Color(0, 165, 224);
    int temp1, temp2;
    boolean tempbool = true;
    private void btnNewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewgameActionPerformed



        pnMain.removeAll();
        pnMain.repaint();

        lbTime.setForeground(new Color(0, 153, 153));


        String ssize;
        String sdiff;
        if (size == 0) {
            ssize = "";
        } else {
            ssize = size + "";
        }
        if (diff == 0) {
            sdiff = "";
        } else {
            sdiff = diff + "";
        }
        List<Question> sq = q.AdvancedSearch(ssize + "", sdiff + "", "");
        if (sq.size() == 0) {
            JOptionPane.showMessageDialog(this, "No question have difficult and size :(, please choose again.");
            return;
        } else {
            //question = q.getQuestionByID("normal-66-005");
            Random generator = new Random();
            int roll;

            roll = generator.nextInt(sq.size());
            tempbool = !tempbool;
            if (tempbool) {
                temp1 = roll;
                if (temp2 == roll) {
                    roll = generator.nextInt(sq.size());
                }
            } else {
                temp2 = roll;
                if (temp1 == roll) {
                    roll = generator.nextInt(sq.size());
                }
            }


            question = sq.get(roll);
            btnFinsh.setEnabled(true);
            btnFinsh.setEnabled(true);
            btnPause.setEnabled(true);
            btnResume.setEnabled(true);
        }




        final String s = question.getQuestionCode();
        pnP = new pnPlay();
        pnP.setWords(s);
        pnP.SetColor(c);
        pnP.setKeywords(question.getQuestionKeyAcross() + question.getQuestionKeyDown());
        pnP.setSizexy(question.getQuestionSize());
        txtHintAcross.setText(question.getQuestionHintAcross());
        txtHintDown.setText(question.getQuestionHintDown());
        lbQuestionName.setText("Question: " + question.getQuestionTitle());
        totalword = question.getQuestionKeyAcross().split(";").length + question.getQuestionKeyDown().split(";").length;
        lbTotalword.setText("Total words: " + totalword);
        lbQuestionID.setText("Question ID: " + question.getQuestionID());
        pnMain.add(pnP);

        //   pnP.setSize(300, 300);
        pnP.setVisible(true);
        pnP.Draw();
        pack();
        ss = totalword * 60;
        t.start();

    }//GEN-LAST:event_btnNewgameActionPerformed
    int b, cc, d, e = 0;

    private String display(int second) {
        if (second > 0 && second < 86399) {
            b = second / 3600;
            cc = second % 3600;
            d = cc / 60;
            e = cc % 60;
        }
        //  return b + ":" + d + ":" + e;
        return d + ":" + e;
    }

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        dlgAbout cp = new dlgAbout(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void mnNewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNewQuestionActionPerformed
        dlgNewQuestionFinal cp = new dlgNewQuestionFinal(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_mnNewQuestionActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        dlgHighScore cp = new dlgHighScore(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void mnViewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnViewQuestionActionPerformed
        dlgViewQuestion cp = new dlgViewQuestion(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_mnViewQuestionActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        dlgOption cp = new dlgOption(this, true);
        cp.setVisible(true);
        size = cp.getSizez();
        diff = cp.getDiff();
        lbInfo.setText("Question next: Diff " + diff + "; Size:" + size);


    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        btnResume.setVisible(true);
        btnPause.setVisible(false);
//        dlgLogin cp = new dlgLogin(this, true);
//        cp.setVisible(true);
        //if (t != null) {
        t.stop();
        //}
    }//GEN-LAST:event_btnPauseActionPerformed
    MP3 mp3 = new MP3("data/sona.mp3");
    private void btnMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicActionPerformed

        mp3.play();
    }//GEN-LAST:event_btnMusicActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        btnPause.setVisible(true);
        btnResume.setVisible(false);
        t.restart();
    }//GEN-LAST:event_btnResumeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mp3.close();

    }//GEN-LAST:event_jButton1ActionPerformed
    boolean show = true;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (show) {
            jPanel4.setVisible(false);
            //   jButton2.setText("> Show");
            show = !show;
        } else {
            jPanel4.setVisible(true);
            //  jButton2.setText("< Hide");
            show = !show;
        }
        //  this.setSize(WIDTH-100, WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    //change color rbg(0,165,224)
    private void btnColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorGreenActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(0, 165, 224);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();

    }//GEN-LAST:event_btnColorGreenActionPerformed

    //181-96-166
    private void btnChangeColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeColor2ActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(181, 96, 166);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();
    }//GEN-LAST:event_btnChangeColor2ActionPerformed
    //246-83-20
    private void btnChangeColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeColor3ActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(246, 83, 20);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();
    }//GEN-LAST:event_btnChangeColor3ActionPerformed

    //255-187-0
    private void btnChangeColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeColor4ActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(255, 187, 0);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();
    }//GEN-LAST:event_btnChangeColor4ActionPerformed

    //124 187 0
    private void btnChangeColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeColor5ActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(124, 187, 0);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();
    }//GEN-LAST:event_btnChangeColor5ActionPerformed

    private void btnFinshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinshActionPerformed

        finish();
    }//GEN-LAST:event_btnFinshActionPerformed
    private void finish() {
        Records record = new Records();
        String ques = question.getQuestionID();
        int user = userID;
        btnFinsh.setEnabled(false);
        int time = totalword * 60 - ss;
        int score = (ss * pnP.getPoint()) / totalword;
        record.createRecord(new Record(ques, user, time, score));
        //JOptionPane.showMessageDialog(rootPane, pnP.getPoint());
////         dlgFinish cp = new dlgFinish(this, true);
////         cp.setPoint(pnP.getPoint());
////         cp.setQuestion(question.getQuestionTitle());
////         cp.setTime(ss);
        t.stop();
        dlgFinish cp = new dlgFinish(question.getQuestionTitle(), score, time);
        cp.setVisible(true);
    }
    //color 107 107 107
    private void btnChangecolor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangecolor6ActionPerformed
        pnMain.removeAll();
        pnMain.repaint();
        c = new Color(107, 107, 107);
        pnP.SetColor(c);
        pnMain.add(pnP);
        pnP.setVisible(true);
        pnP.DrawAgaint(pnP.getCode());
        pack();
    }//GEN-LAST:event_btnChangecolor6ActionPerformed

    private void mnViewallrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnViewallrecordActionPerformed
        dlgViewRecord cp = new dlgViewRecord(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_mnViewallrecordActionPerformed

    //Show dialog record view
    private void mnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecordActionPerformed
    }//GEN-LAST:event_mnRecordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        dlgLogin cp = new dlgLogin(this, true);
        cp.setVisible(true);

        username = cp.getUsername();
        role = cp.getRole();
        userID = cp.getId();

        if (role == 2) {
            btnLogin.setVisible(false);
            txtLogin.setText("Hello: " + username);
            mnQuestion.setVisible(false);
            mnRecord.setVisible(false);
            btnSave.setVisible(true);
            mnProfile.setVisible(true);
            mnAccount.setVisible(true);
        }
        if (role == 3) {
            btnLogin.setVisible(true);
            txtLogin.setText("Hello: " + "Guest");
            mnQuestion.setVisible(false);
            mnRecord.setVisible(false);
            btnSave.setVisible(false);
            mnProfile.setVisible(false);
            mnAccount.setVisible(false);
        }
        if (role == 1) {
            btnLogin.setVisible(false);
            txtLogin.setText("Hello: " + username);
            mnQuestion.setVisible(true);
            mnRecord.setVisible(true);
            btnSave.setVisible(true);
            mnProfile.setVisible(true);
            mnAccount.setVisible(false);
        }
        int iddelete = 0;


        for (Saved s : saved.getAllSaved()) {

            if (s.getSaveUserID() == userID) {
                if (JOptionPane.showConfirmDialog(rootPane, "Do you want load saved game?", "Save game", JOptionPane.OK_CANCEL_OPTION) == 0) {

                    iddelete = s.getSaveID();
                    Question ques = new Questions().getQuestionByID(s.getQuestionID());
                    pnMain.removeAll();
                    pnMain.repaint();

                    lbTime.setForeground(new Color(0, 153, 153));


                    String ssize;
                    String sdiff;
                    if (size == 0) {
                        ssize = "";
                    } else {
                        ssize = size + "";
                    }
                    if (diff == 0) {
                        sdiff = "";
                    } else {
                        sdiff = diff + "";
                    }
                    List<Question> sq = q.AdvancedSearch(ssize + "", sdiff + "", "");
                    if (sq.size() == 0) {
                        JOptionPane.showMessageDialog(this, "No question have difficult and size :(, please choose again.");
                        return;
                    } else {
                        //question = q.getQuestionByID("normal-66-005");
                        Random generator = new Random();
                        int roll;

                        roll = generator.nextInt(sq.size());
                        tempbool = !tempbool;
                        if (tempbool) {
                            temp1 = roll;
                            if (temp2 == roll) {
                                roll = generator.nextInt(sq.size());
                            }
                        } else {
                            temp2 = roll;
                            if (temp1 == roll) {
                                roll = generator.nextInt(sq.size());
                            }
                        }


                        question = sq.get(roll);
                        btnFinsh.setEnabled(true);
                        btnFinsh.setEnabled(true);
                        btnPause.setEnabled(true);
                        btnResume.setEnabled(true);
                    }




                    final String s1 = s.getQuestionID();
                    pnP = new pnPlay();
                    pnP.setWords(ques.getQuestionKeyAcross() + ques.getQuestionKeyDown());
                    pnP.SetColor(c);
                    pnP.setKeywords(ques.getQuestionKeyAcross() + ques.getQuestionKeyDown());
                    pnP.setSizexy(ques.getQuestionSize());
                    txtHintAcross.setText(ques.getQuestionHintAcross());
                    txtHintDown.setText(ques.getQuestionHintDown());
                    lbQuestionName.setText("Question: " + ques.getQuestionTitle());
                    totalword = ques.getQuestionKeyAcross().split(";").length + ques.getQuestionKeyDown().split(";").length;
                    lbTotalword.setText("Total words: " + totalword);
                    lbQuestionID.setText("Question ID: " + ques.getQuestionID());
                    pnMain.add(pnP);

                    //   pnP.setSize(300, 300);
                    pnP.setVisible(true);
                    pnP.DrawAgaint(s.getSavedCode());
                    pack();
                    ss = s.getSaveTime();
                    t.start();
                    break;
                }
            }
        }
        saved.DeleteSaved(iddelete);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Do you want save this game and exit?", "Save game", JOptionPane.OK_CANCEL_OPTION) == 0) {

            saved.createSaved(new Saved(userID, question.getQuestionID(), pnP.getCode(), ss));
              System.exit(0);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeColor2;
    private javax.swing.JButton btnChangeColor3;
    private javax.swing.JButton btnChangeColor4;
    private javax.swing.JButton btnChangeColor5;
    private javax.swing.JButton btnChangecolor6;
    private javax.swing.JButton btnColorGreen;
    private javax.swing.JButton btnFinsh;
    private javax.swing.JButton btnHighScore;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMusic;
    private javax.swing.JButton btnNewgame;
    private javax.swing.JButton btnOption;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbQuestionID;
    private javax.swing.JLabel lbQuestionName;
    private javax.swing.JTextField lbTime;
    private javax.swing.JLabel lbTotalword;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenu mnAccount;
    private javax.swing.JMenuItem mnHistory;
    private javax.swing.JMenuItem mnNewQuestion;
    private javax.swing.JMenuItem mnProfile;
    private javax.swing.JMenu mnQuestion;
    private javax.swing.JMenu mnRecord;
    private javax.swing.JMenuItem mnViewQuestion;
    private javax.swing.JMenuItem mnViewallrecord;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTextArea txtHintAcross;
    private javax.swing.JTextArea txtHintDown;
    private javax.swing.JLabel txtLogin;
    // End of variables declaration//GEN-END:variables
}
