/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eprojectsemii;

import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.io.File;
import javax.print.attribute.standard.Media;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Fozg
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        btnResume.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar(){

            ImageIcon icon = new ImageIcon("src/icons/bgmenu.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnNewgame = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnOption = new javax.swing.JButton();
        btnHighScore = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMusic = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/icons/bgtop2.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/icons/crossword.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        pnMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnNewQuestion = new javax.swing.JMenuItem();
        mnViewQuestion = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 540));
        setMinimumSize(new java.awt.Dimension(850, 540));
        setPreferredSize(new java.awt.Dimension(850, 540));
        setResizable(false);

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);

        btnNewgame.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnNewgame.setForeground(new java.awt.Color(255, 255, 255));
        btnNewgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newgame.png"))); // NOI18N
        btnNewgame.setToolTipText("");
        btnNewgame.setBorderPainted(false);
        btnNewgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewgame.setFocusable(false);
        btnNewgame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewgame.setMaximumSize(new java.awt.Dimension(117, 57));
        btnNewgame.setMinimumSize(new java.awt.Dimension(117, 57));
        btnNewgame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewgameActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewgame);

        btnPause.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnPause.setForeground(new java.awt.Color(255, 255, 255));
        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pause.png"))); // NOI18N
        btnPause.setBorderPainted(false);
        btnPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPause.setFocusable(false);
        btnPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPause);

        btnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resume.png"))); // NOI18N
        btnResume.setBorderPainted(false);
        btnResume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResume.setFocusable(false);
        btnResume.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResume.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnResume);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 96, 166));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/time2.png"))); // NOI18N
        jLabel3.setText("00:00");
        jToolBar1.add(jLabel3);

        btnOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/option.png"))); // NOI18N
        btnOption.setFocusable(false);
        btnOption.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOption.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOption);

        btnHighScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hightsocre.png"))); // NOI18N
        btnHighScore.setFocusable(false);
        btnHighScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighScore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHighScore);

        jPanel1.setOpaque(false);

        jLabel2.setText("Question");
        jPanel1.add(jLabel2);

        btnMusic.setText("Play music");
        btnMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicActionPerformed(evt);
            }
        });
        jPanel1.add(btnMusic);

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jLabel1.setText("Status");
        jPanel2.add(jLabel1);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("New Question");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Question");

        mnNewQuestion.setText("New Question");
        mnNewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNewQuestionActionPerformed(evt);
            }
        });
        jMenu2.add(mnNewQuestion);

        mnViewQuestion.setText("View Question");
        mnViewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnViewQuestionActionPerformed(evt);
            }
        });
        jMenu2.add(mnViewQuestion);

        jMenuItem4.setText("Delete question");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        NewJInternalFrame fnq = new NewJInternalFrame();
//        dtpMain.add(fnq);
//        fnq.show();
        dlgLogin cp = new dlgLogin(this, true);
        cp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btnNewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewgameActionPerformed
//        pnMain.setSize(200,200);
//        pnMain.setLayout(new GridLayout(6, 6));
//      
//       
//        for (int i = 0; i < 6; i++) {
//               for (int j = 0; j < 6; j++) {
//               JButton jb = new JButton();
//                jb.setSize(20, 20);
//                jb.setText("A");
//                pnMain.add(jb);
//            }
//        }
//        pnMain.removeAll();
//        pnMain.repaint();
//        String s="*;*;*;*;A;A;A;A;*;*;*;*;*;*;A;A;A;A;*;*;*;*;*;*;A;A;A;A;*;*;*;*;*;*;A;A;A;A;*;*;*;*;*;*;A;A;";
//        pnPlay pnP = new  pnPlay(s,6);
//        pnMain.setSize(400, 400);
//     //   pnP.setSize(400, 400);
//        pnMain.add(pnP);
//        pnP.setVisible(true);
//        
//        pack();     
        //  pnMain.removeAll();
        pnMain.removeAll();
        JButton jbb = new JButton();
        jbb.setText("Acbc");
        pnMain.add(jbb);

        jbb.setVisible(true);

        String s = "-;-;-;-;A;A;A;A;-;-;-;-;-;-;A;A;A;A;-;-;-;-;-;-;A;A;A;A;-;-;-;-;-;-;A;A;A;A;-;-;-;-;-;-;A;A;";
        pnPlay pnP = new pnPlay();
        pnP.setWords(s);
        pnP.setSizexy(6);

        pnMain.add(pnP);

        //   pnP.setSize(300, 300);
        pnP.setVisible(true);
        pnP.Draw();
        pack();

    }//GEN-LAST:event_btnNewgameActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        dlgAbout cp = new dlgAbout(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void mnNewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNewQuestionActionPerformed
        dlgNewQuestionFinal cp = new dlgNewQuestionFinal(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_mnNewQuestionActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        dlgHighScore cp = new dlgHighScore(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void mnViewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnViewQuestionActionPerformed
        dlgViewQuestion cp = new dlgViewQuestion(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_mnViewQuestionActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        dlgOption cp = new dlgOption(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        btnResume.setVisible(true);
        btnPause.setVisible(false);
        dlgLogin cp = new dlgLogin(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_btnPauseActionPerformed
    MP3 mp3 = new MP3("src/sona.mp3");
    private void btnMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicActionPerformed

        mp3.play();
    }//GEN-LAST:event_btnMusicActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        btnPause.setVisible(true);
        btnResume.setVisible(false);
    }//GEN-LAST:event_btnResumeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mp3.close();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHighScore;
    private javax.swing.JButton btnMusic;
    private javax.swing.JButton btnNewgame;
    private javax.swing.JButton btnOption;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem mnNewQuestion;
    private javax.swing.JMenuItem mnViewQuestion;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
