/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eprojectsemii;

import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Fozg
 */
public class size66 extends javax.swing.JPanel {

    /**
     * Creates new form size66
     */
    public size66() {
        initComponents();
        j1.setHorizontalAlignment(JTextField.CENTER);
        j2.setHorizontalAlignment(JTextField.CENTER);
        j3.setHorizontalAlignment(JTextField.CENTER);
        j4.setHorizontalAlignment(JTextField.CENTER);
        j5.setHorizontalAlignment(JTextField.CENTER);
        j6.setHorizontalAlignment(JTextField.CENTER);
        j7.setHorizontalAlignment(JTextField.CENTER);
        j8.setHorizontalAlignment(JTextField.CENTER);
        j9.setHorizontalAlignment(JTextField.CENTER);
        j9.setHorizontalAlignment(JTextField.CENTER);
        j10.setHorizontalAlignment(JTextField.CENTER);
        j11.setHorizontalAlignment(JTextField.CENTER);
        j12.setHorizontalAlignment(JTextField.CENTER);
        j13.setHorizontalAlignment(JTextField.CENTER);
        j14.setHorizontalAlignment(JTextField.CENTER);
        j15.setHorizontalAlignment(JTextField.CENTER);
        j16.setHorizontalAlignment(JTextField.CENTER);
        j17.setHorizontalAlignment(JTextField.CENTER);
        j18.setHorizontalAlignment(JTextField.CENTER);
        j19.setHorizontalAlignment(JTextField.CENTER);
        j20.setHorizontalAlignment(JTextField.CENTER);
        j21.setHorizontalAlignment(JTextField.CENTER);
        j22.setHorizontalAlignment(JTextField.CENTER);
        j23.setHorizontalAlignment(JTextField.CENTER);
        j24.setHorizontalAlignment(JTextField.CENTER);
        j25.setHorizontalAlignment(JTextField.CENTER);
        j26.setHorizontalAlignment(JTextField.CENTER);
        j27.setHorizontalAlignment(JTextField.CENTER);
        j28.setHorizontalAlignment(JTextField.CENTER);
        j29.setHorizontalAlignment(JTextField.CENTER);
        j30.setHorizontalAlignment(JTextField.CENTER);
        j31.setHorizontalAlignment(JTextField.CENTER);
        j32.setHorizontalAlignment(JTextField.CENTER);
        j33.setHorizontalAlignment(JTextField.CENTER);
        j34.setHorizontalAlignment(JTextField.CENTER);
        j35.setHorizontalAlignment(JTextField.CENTER);
        j36.setHorizontalAlignment(JTextField.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j2 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j19 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j29 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        cbView = new javax.swing.JCheckBox();

        j2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j1KeyPressed(evt);
            }
        });

        j4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        j34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        cbView.setText("Last view to create question");
        cbView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbView)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnPreview)
                    .addComponent(btnEdit))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void clear(){
        j1.setText("");        // TODO add your handling code here:
        j2.setText("");        // TODO add your handling code here:
        j3.setText("");        // TODO add your handling code here:
        j4.setText("");        // TODO add your handling code here:
        j5.setText("");        // TODO add your handling code here:
        j6.setText("");        // TODO add your handling code here:
        j7.setText("");        // TODO add your handling code here:
        j8.setText("");        // TODO add your handling code here:
        j9.setText("");        // TODO add your handling code here:
        j10.setText("");        // TODO add your handling code here:
        j11.setText("");        // TODO add your handling code here:
        j12.setText("");        // TODO add your handling code here:
        j13.setText("");        // TODO add your handling code here:
        j14.setText("");        // TODO add your handling code here:
        j15.setText("");        // TODO add your handling code here:
        j16.setText("");        // TODO add your handling code here:
        j17.setText("");        // TODO add your handling code here:
        j18.setText("");        // TODO add your handling code here:
        j19.setText("");        // TODO add your handling code here:
        j20.setText("");        // TODO add your handling code here:
        j21.setText("");        // TODO add your handling code here:
        j22.setText("");        // TODO add your handling code here:
        j23.setText("");        // TODO add your handling code here:
        j24.setText("");        // TODO add your handling code here:
        j25.setText("");        // TODO add your handling code here:
        j26.setText("");        // TODO add your handling code here:
        j27.setText("");        // TODO add your handling code here:
        j28.setText("");        // TODO add your handling code here:
        j29.setText("");        // TODO add your handling code here:
        j30.setText("");        // TODO add your handling code here:
        j31.setText("");        // TODO add your handling code here:
        j32.setText("");        // TODO add your handling code here:
        j33.setText("");        // TODO add your handling code here:
        j34.setText("");        // TODO add your handling code here:
        j35.setText("");        // TODO add your handling code here:
        j36.setText("");        // TODO add your handling code here:
        setShowforAll();
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void setHide(JTextField j) {
        if ("".equals(j.getText())) {
            j.setVisible(false);
        } else {
            j.setText(convert(j));
            j.setEnabled(false);
        }
    }

    private void setShow(JTextField j) {
        j.setVisible(true);
        j.setEnabled(true);
    }
    private String convert(JTextField j){
        if ("".equals(j.getText())){
            return "*";
        }
        else {
           
            String sone = j.getText().substring(1);
            return j.getText().toUpperCase().charAt(0)+"";
        }
    }

    public String getCode() {
        String code = "";
        code += convert(j1)+";";
        code += convert(j2)+";";
        code += convert(j3)+";";
        code += convert(j4)+";";
        code += convert(j5)+";";
        code += convert(j6)+";";
        code += convert(j7)+";";
        code += convert(j8)+";";
        code += convert(j9)+";";
        code += convert(j10)+";";
        code += convert(j11)+";";
        code += convert(j12)+";";
        code += convert(j13)+";";
        code += convert(j14)+";";
        code += convert(j15)+";";
        code += convert(j16)+";";
        code += convert(j17)+";";
        code += convert(j18)+";";
        code += convert(j19)+";";
        code += convert(j20)+";";
        code += convert(j21)+";";
        code += convert(j22)+";";
        code += convert(j23)+";";
        code += convert(j24)+";";
        code += convert(j25)+";";
        code += convert(j26)+";";
        code += convert(j27)+";";
        code += convert(j28)+";";
        code += convert(j29)+";";
        code += convert(j30)+";";
        code += convert(j31)+";";
        code += convert(j32)+";";
        code += convert(j33)+";";
        code += convert(j34)+";";
        code += convert(j35)+";";
        code += convert(j36)+";";
        
        return code;
    }
    //action preview ..
    private void preview(){
         setHide(j1);
        setHide(j2);
        setHide(j3);
        setHide(j4);
        setHide(j5);
        setHide(j6);
        setHide(j7);
        setHide(j8);
        setHide(j9);
        setHide(j10);
        setHide(j11);
        setHide(j12);
        setHide(j13);
        setHide(j14);
        setHide(j15);
        setHide(j16);
        setHide(j17);
        setHide(j18);
        setHide(j19);
        setHide(j20);
        setHide(j21);
        setHide(j22);
        setHide(j23);
        setHide(j24);
        setHide(j25);
        setHide(j26);
        setHide(j27);
        setHide(j28);
        setHide(j29);
        setHide(j30);
        setHide(j31);
        setHide(j32);
        setHide(j33);
        setHide(j34);
        setHide(j35);
        setHide(j36);
    }
    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // this.setLayout();
       preview();

    }//GEN-LAST:event_btnPreviewActionPerformed
    // un preview..
    private void setShowforAll() {
        setShow(j1);
        setShow(j2);
        setShow(j3);
        setShow(j4);
        setShow(j5);
        setShow(j6);
        setShow(j7);
        setShow(j8);
        setShow(j9);
        setShow(j10);
        setShow(j11);
        setShow(j12);
        setShow(j13);
        setShow(j14);
        setShow(j15);
        setShow(j16);
        setShow(j17);
        setShow(j18);
        setShow(j19);
        setShow(j20);
        setShow(j21);
        setShow(j22);
        setShow(j23);
        setShow(j24);
        setShow(j25);
        setShow(j26);
        setShow(j27);
        setShow(j28);
        setShow(j29);
        setShow(j30);
        setShow(j31);
        setShow(j32);
        setShow(j33);
        setShow(j34);        
        setShow(j35);
        setShow(j36);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setShowforAll();

    }//GEN-LAST:event_btnEditActionPerformed

    private void cbViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViewActionPerformed
        if (cbView.isSelected()){
            preview();
        }else {
            setShowforAll();
        }
             
    }//GEN-LAST:event_cbViewActionPerformed

    private void j1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j1KeyPressed
        String s = j1.getText().toUpperCase();
        if (!"".equals(j1.getText()))
       // j1.setText( s.toUpperCase().charAt(0)+"");
        j1.setText(s.toUpperCase().substring(1));
  
     
    }//GEN-LAST:event_j1KeyPressed

    //return checkbox finsish create is cheked ?
    public boolean getLastViewChecked(){
        return cbView.isSelected();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPreview;
    private javax.swing.JCheckBox cbView;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j19;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j29;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j9;
    // End of variables declaration//GEN-END:variables
}
